In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

In [ ]:
for x in arr:
    print(x)


In [ ]:
arr = np.array((1,2,3,4)) #uni-dimensional
print(arr)

In [ ]:
arr = np.array([[1,2,3] , [4,3,2]]) #2-D
print(arr)
print(arr[0])
print(arr[0][0])

In [ ]:
arr = np.array([[[1,2],[2,3]],[[1,3], [4,1]]]) # 3_D
print(arr)

In [ ]:
# Check how many dimensions the arrays have:


a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
e = np.array([[[[1, 2, 3], [4, 5, 6]], [[11, 3, 4], [4, 2, 6]]] , [[[13, 2, 31], [4, 53, 61]], [[11, 2, 3], [43, 5, 6]]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)
print(e)

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

In [ ]:

arr = np.array([1, 2, 3, 4])

print(arr[0] + arr[1])

In [ ]:

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4])
print('5th element on 2nd row: ', arr[1][4])

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:5:2])

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[2::2])

In [ ]:
#Slicing 2-D Arrays

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

In [6]:
# From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2 # which elements
, 1:4] #which indexs
)

[[2 3 4]
 [7 8 9]]


In [9]:
arr = np.array([1.1, 2, 3, 4])

print(arr.dtype)


float64


In [11]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [10]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [12]:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [14]:
#Converting Data Type on Existing Arrays

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [15]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [16]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [ ]:
# Data Types in NumPy
# NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

# Below is a list of all data types in NumPy and the characters used to represent them.

# i - integer
# b - boolean
# u - unsigned integer
# f - float
# c - complex float
# m - timedelta
# M - datetime
# O - object
# S - string
# U - unicode string
# V - fixed chunk of memory for other type ( void )

In [17]:
#Copy
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [19]:
# View
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [20]:

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [21]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [34]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8 ]])

print(arr)
print(arr.shape)
# first result is row and the second is the column
#Integers at every index tells about the number of elements the corresponding dimension has.



[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [31]:
arr = np.array([1, 2, 3, 4], ndmin=3)

print(arr)
print('shape of array :', arr.shape)

[[[1 2 3 4]]]
shape of array : (1, 1, 4)


In [38]:
# Convert the following 1-D array with 12 elements into a 2-D array.



arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3 )

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [39]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [40]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


In [41]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
