In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

In [ ]:
for x in arr:
    print(x)


In [11]:
arr = np.array((1,2,3,4)) #uni-dimensional
print(arr)

[1 2 3 4]


In [27]:
arr = np.array([[1,2,3] , [4,3,2]]) #2-D
print(arr)
print(arr[0])
print(arr[0][0])

[[1 2 3]
 [4 3 2]]
[1 2 3]
1


In [16]:
arr = np.array([[[1,2],[2,3]],[[1,3], [4,1]]]) # 3_D
print(arr)

[[[1 2]
  [2 3]]

 [[1 3]
  [4 1]]]


In [20]:
# Check how many dimensions the arrays have:


a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
e = np.array([[[[1, 2, 3], [4, 5, 6]], [[11, 3, 4], [4, 2, 6]]] , [[[13, 2, 31], [4, 53, 61]], [[11, 2, 3], [43, 5, 6]]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)
print(e)

0
1
2
3
4
[[[[ 1  2  3]
   [ 4  5  6]]

  [[11  3  4]
   [ 4  2  6]]]


 [[[13  2 31]
   [ 4 53 61]]

  [[11  2  3]
   [43  5  6]]]]


In [22]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5
[[[[1 2 3 4]]]]


In [29]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1
